[google]
client_id = "350303331842-dhq1edm8pdjvea02ngi6grh99r1j2h13.apps.googleusercontent.com"
client_secret = "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"
project_id = "spam-detection-463209"
redirect_uri = "https://email-spam-detectionn.streamlit.app"
